### ISSUE TITLE
Wrong MSRV

### ISSUE THREAD

**Issue by cospectrum** [image-rs/image#2168]
Failed to compile using `1.67.1` rustc.
The MSRV seems to be `1.70.0`.

## Expected
successful compilation

## Actual behaviour
compilation failed

## Reproduction steps
```sh
rustup install 1.67.1 && cargo new reproduce && cd reproduce && cargo add image && cargo +1.67.1 check
```

**Comment by cospectrum** [comment]
Perhaps dependencies are to blame. I noticed it during recent CI on `imageproc`

**Comment by fintelia** [comment]
Our CI checks with the MSRV version, but we use -Zminimal-version so that we pull in dependency versions with suitably old MSRVs

**Comment by cospectrum** [comment]
If you think this is the right approach, then that's okay.
